from django.db import models

# Create your models here.
class user(models.Model):
    quizlist=models.TextField(null=True)
    username=models.CharField(max_length=30)
    password=models.CharField(max_length=50)
    succesrate=models.IntegerField(null=True)
    objects = models.Manager()
class question(models.Model):
    text=models.CharField(max_length=100)
    correct_answer=models.CharField(max_length=15)
    option1=models.CharField(max_length=15,null=True)
    option2=models.CharField(max_length=15,null=True)
    option3=models.CharField(max_length=15,null=True)
    option4=models.CharField(max_length=15,null=True)
    number_of_fails=models.IntegerField(null=True)
    number_of_passes=models.IntegerField(null=True)
    total_number=models.IntegerField(null=True)
    category=models.CharField(max_length=15)
    difficulty=models.CharField(max_length=15)
    text1=models.CharField(max_length=200)
    fail_percent=models.IntegerField(null=True)
    objects = models.Manager()
class Quiz(models.Model):
    name=models.TextField()
    category=models.CharField(max_length=15)
    difficulty=models.CharField(max_length=15)
    q1=models.ForeignKey(question,related_name='%(class)s_requests_created10',on_delete=models.CASCADE)
    q2=models.ForeignKey(question,related_name='%(class)s_requests_created9',on_delete=models.CASCADE)
    q3=models.ForeignKey(question,related_name='%(class)s_requests_created8',on_delete=models.CASCADE)
    q4=models.ForeignKey(question,related_name='%(class)s_requests_created7',on_delete=models.CASCADE)
    q5=models.ForeignKey(question,related_name='%(class)s_requests_created6',on_delete=models.CASCADE)
    q6=models.ForeignKey(question,related_name='%(class)s_requests_created5',on_delete=models.CASCADE)
    q7=models.ForeignKey(question,related_name='%(class)s_requests_created4',on_delete=models.CASCADE)
    q8=models.ForeignKey(question,related_name='%(class)s_requests_created3',on_delete=models.CASCADE)
    q9=models.ForeignKey(question,related_name='%(class)s_requests_created2',on_delete=models.CASCADE)
    q10=models.ForeignKey(question,related_name='%(class)s_requests_created1',on_delete=models.CASCADE)
    objects = models.Manager()
