# Generated by Django 4.2.7 on 2023-12-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_userprofile_finished_quizzes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='finished_quizzes',
            field=models.ManyToManyField(blank=True, default=None, to='app.quiz'),
        ),
    ]
