# Generated by Django 4.2.1 on 2024-01-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_userprofile_finished_quizzes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='fail_percent',
        ),
    ]
